using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace WebProjectsWithOnionArchitecture.Infrastruct.Migrations
{
    public partial class Migration_3 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Accountid",
                table: "CrmAccounts");

            migrationBuilder.DropColumn(
                name: "Statecode",
                table: "CrmAccounts");

            migrationBuilder.RenameColumn(
                name: "OdataEtag",
                table: "CrmAccounts",
                newName: "OdataNextLink");

            migrationBuilder.RenameColumn(
                name: "Name",
                table: "CrmAccounts",
                newName: "OdataContext");

            migrationBuilder.CreateTable(
                name: "CrmAccountValue",
                columns: table => new
                {
                    Guid = table.Column<Guid>(type: "TEXT", nullable: false),
                    OdataEtag = table.Column<string>(type: "TEXT", nullable: true),
                    customertypecode = table.Column<int>(type: "INTEGER", nullable: true),
                    industrycode = table.Column<int>(type: "INTEGER", nullable: true),
                    address2_addresstypecode = table.Column<int>(type: "INTEGER", nullable: false),
                    new_gncellemearamas = table.Column<int>(type: "INTEGER", nullable: true),
                    merged = table.Column<bool>(type: "INTEGER", nullable: false),
                    new_adres = table.Column<string>(type: "TEXT", nullable: true),
                    new_sonaktivitetarihi = table.Column<DateTime>(type: "TEXT", nullable: true),
                    territorycode = table.Column<int>(type: "INTEGER", nullable: false),
                    _new_firmadepartman_value = table.Column<string>(type: "TEXT", nullable: true),
                    new_letiimdili = table.Column<int>(type: "INTEGER", nullable: true),
                    name = table.Column<string>(type: "TEXT", nullable: true),
                    importsequencenumber = table.Column<int>(type: "INTEGER", nullable: false),
                    _owningbusinessunit_value = table.Column<string>(type: "TEXT", nullable: true),
                    _owninguser_value = table.Column<string>(type: "TEXT", nullable: true),
                    _primarycontactid_value = table.Column<string>(type: "TEXT", nullable: true),
                    new_frsatkayna = table.Column<int>(type: "INTEGER", nullable: true),
                    lastusedincampaign = table.Column<DateTime>(type: "TEXT", nullable: true),
                    statecode = table.Column<int>(type: "INTEGER", nullable: false),
                    _new_lkeid_value = table.Column<string>(type: "TEXT", nullable: true),
                    donotpostalmail = table.Column<bool>(type: "INTEGER", nullable: false),
                    _ownerid_value = table.Column<string>(type: "TEXT", nullable: true),
                    accountratingcode = table.Column<int>(type: "INTEGER", nullable: false),
                    _new_kategori_value = table.Column<string>(type: "TEXT", nullable: true),
                    new_cari_kod = table.Column<string>(type: "TEXT", nullable: true),
                    preferredcontactmethodcode = table.Column<int>(type: "INTEGER", nullable: false),
                    _territoryid_value = table.Column<string>(type: "TEXT", nullable: true),
                    _new_ehirid_value = table.Column<string>(type: "TEXT", nullable: true),
                    _new_alt_kategori_value = table.Column<string>(type: "TEXT", nullable: true),
                    description = table.Column<string>(type: "TEXT", nullable: true),
                    customersizecode = table.Column<int>(type: "INTEGER", nullable: false),
                    _new_sektorid_value = table.Column<string>(type: "TEXT", nullable: true),
                    donotemail = table.Column<bool>(type: "INTEGER", nullable: false),
                    openrevenue_date = table.Column<DateTime>(type: "TEXT", nullable: false),
                    _new_ilce_value = table.Column<string>(type: "TEXT", nullable: true),
                    new_belgekonumu = table.Column<bool>(type: "INTEGER", nullable: false),
                    new_lekodu = table.Column<string>(type: "TEXT", nullable: true),
                    address2_shippingmethodcode = table.Column<int>(type: "INTEGER", nullable: false),
                    timezoneruleversionnumber = table.Column<int>(type: "INTEGER", nullable: true),
                    address1_addressid = table.Column<string>(type: "TEXT", nullable: true),
                    address2_freighttermscode = table.Column<int>(type: "INTEGER", nullable: false),
                    statuscode = table.Column<int>(type: "INTEGER", nullable: false),
                    createdon = table.Column<DateTime>(type: "TEXT", nullable: false),
                    new_verginumaras = table.Column<string>(type: "TEXT", nullable: true),
                    address1_stateorprovince = table.Column<string>(type: "TEXT", nullable: true),
                    opendeals_date = table.Column<DateTime>(type: "TEXT", nullable: false),
                    donotsendmm = table.Column<bool>(type: "INTEGER", nullable: false),
                    donotfax = table.Column<bool>(type: "INTEGER", nullable: false),
                    _new_projetakmlar_value = table.Column<string>(type: "TEXT", nullable: true),
                    donotbulkpostalmail = table.Column<bool>(type: "INTEGER", nullable: false),
                    versionnumber = table.Column<string>(type: "TEXT", nullable: true),
                    modifiedon = table.Column<DateTime>(type: "TEXT", nullable: false),
                    telephone1 = table.Column<string>(type: "TEXT", nullable: true),
                    donotphone = table.Column<bool>(type: "INTEGER", nullable: false),
                    _transactioncurrencyid_value = table.Column<string>(type: "TEXT", nullable: true),
                    accountid = table.Column<string>(type: "TEXT", nullable: true),
                    donotbulkemail = table.Column<bool>(type: "INTEGER", nullable: false),
                    creditonhold = table.Column<bool>(type: "INTEGER", nullable: false),
                    exchangerate = table.Column<double>(type: "REAL", nullable: false),
                    new_cari_unvan = table.Column<string>(type: "TEXT", nullable: true),
                    _modifiedby_value = table.Column<string>(type: "TEXT", nullable: true),
                    businesstypecode = table.Column<int>(type: "INTEGER", nullable: false),
                    _createdby_value = table.Column<string>(type: "TEXT", nullable: true),
                    new_id = table.Column<string>(type: "TEXT", nullable: true),
                    ownershipcode = table.Column<int>(type: "INTEGER", nullable: false),
                    new_slavarm = table.Column<bool>(type: "INTEGER", nullable: true),
                    _modifiedonbehalfby_value = table.Column<string>(type: "TEXT", nullable: true),
                    participatesinworkflow = table.Column<bool>(type: "INTEGER", nullable: false),
                    new_etkinlisanskartisayisi = table.Column<int>(type: "INTEGER", nullable: true),
                    accountclassificationcode = table.Column<int>(type: "INTEGER", nullable: false),
                    address2_addressid = table.Column<string>(type: "TEXT", nullable: true),
                    _new_mteritemsilcisiid_value = table.Column<string>(type: "TEXT", nullable: true),
                    new_vergidairesi = table.Column<string>(type: "TEXT", nullable: true),
                    new_gncellemearamatarihi = table.Column<DateTime>(type: "TEXT", nullable: true),
                    new_beldekodu = table.Column<string>(type: "TEXT", nullable: true),
                    address1_composite = table.Column<string>(type: "TEXT", nullable: true),
                    openrevenue_state = table.Column<string>(type: "TEXT", nullable: true),
                    address1_freighttermscode = table.Column<string>(type: "TEXT", nullable: true),
                    telephone3 = table.Column<string>(type: "TEXT", nullable: true),
                    shippingmethodcode = table.Column<string>(type: "TEXT", nullable: true),
                    new_gncellemearamasyapld = table.Column<bool>(type: "INTEGER", nullable: true),
                    address1_longitude = table.Column<string>(type: "TEXT", nullable: true),
                    opendeals_state = table.Column<string>(type: "TEXT", nullable: true),
                    address1_country = table.Column<string>(type: "TEXT", nullable: true),
                    _originatingleadid_value = table.Column<string>(type: "TEXT", nullable: true),
                    new_kontroledildi = table.Column<bool>(type: "INTEGER", nullable: true),
                    creditlimit_base = table.Column<string>(type: "TEXT", nullable: true),
                    websiteurl = table.Column<string>(type: "TEXT", nullable: true),
                    address1_postofficebox = table.Column<string>(type: "TEXT", nullable: true),
                    preferredappointmenttimecode = table.Column<string>(type: "TEXT", nullable: true),
                    timespentbymeonemailandmeetings = table.Column<string>(type: "TEXT", nullable: true),
                    address2_name = table.Column<string>(type: "TEXT", nullable: true),
                    address2_upszone = table.Column<string>(type: "TEXT", nullable: true),
                    primarysatoriid = table.Column<string>(type: "TEXT", nullable: true),
                    entityimage_url = table.Column<string>(type: "TEXT", nullable: true),
                    emailaddress2 = table.Column<string>(type: "TEXT", nullable: true),
                    new_sozlesme_bitis_tarihi = table.Column<string>(type: "TEXT", nullable: true),
                    address2_line1 = table.Column<string>(type: "TEXT", nullable: true),
                    _slaid_value = table.Column<string>(type: "TEXT", nullable: true),
                    address2_city = table.Column<string>(type: "TEXT", nullable: true),
                    address1_upszone = table.Column<string>(type: "TEXT", nullable: true),
                    stockexchange = table.Column<string>(type: "TEXT", nullable: true),
                    entityimage = table.Column<string>(type: "TEXT", nullable: true),
                    _preferredserviceid_value = table.Column<string>(type: "TEXT", nullable: true),
                    _masterid_value = table.Column<string>(type: "TEXT", nullable: true),
                    address2_latitude = table.Column<string>(type: "TEXT", nullable: true),
                    address2_utcoffset = table.Column<string>(type: "TEXT", nullable: true),
                    marketcap_base = table.Column<string>(type: "TEXT", nullable: true),
                    new_durum = table.Column<int>(type: "INTEGER", nullable: true),
                    telephone2 = table.Column<string>(type: "TEXT", nullable: true),
                    paymenttermscode = table.Column<string>(type: "TEXT", nullable: true),
                    address1_line1 = table.Column<string>(type: "TEXT", nullable: true),
                    _modifiedbyexternalparty_value = table.Column<string>(type: "TEXT", nullable: true),
                    entityimageid = table.Column<string>(type: "TEXT", nullable: true),
                    new_randevu_sure = table.Column<string>(type: "TEXT", nullable: true),
                    fax = table.Column<string>(type: "TEXT", nullable: true),
                    stageid = table.Column<string>(type: "TEXT", nullable: true),
                    utcconversiontimezonecode = table.Column<string>(type: "TEXT", nullable: true),
                    onholdtime = table.Column<string>(type: "TEXT", nullable: true),
                    address1_primarycontactname = table.Column<string>(type: "TEXT", nullable: true),
                    yominame = table.Column<string>(type: "TEXT", nullable: true),
                    _defaultpricelevelid_value = table.Column<string>(type: "TEXT", nullable: true),
                    new_le = table.Column<string>(type: "TEXT", nullable: true),
                    address2_telephone2 = table.Column<string>(type: "TEXT", nullable: true),
                    address2_composite = table.Column<string>(type: "TEXT", nullable: true),
                    address2_line3 = table.Column<string>(type: "TEXT", nullable: true),
                    _createdonbehalfby_value = table.Column<string>(type: "TEXT", nullable: true),
                    _createdbyexternalparty_value = table.Column<string>(type: "TEXT", nullable: true),
                    new_letiimdili2 = table.Column<string>(type: "TEXT", nullable: true),
                    openrevenue = table.Column<string>(type: "TEXT", nullable: true),
                    _new_etkinlikprogramid_value = table.Column<string>(type: "TEXT", nullable: true),
                    address1_utcoffset = table.Column<string>(type: "TEXT", nullable: true),
                    primarytwitterid = table.Column<string>(type: "TEXT", nullable: true),
                    sic = table.Column<string>(type: "TEXT", nullable: true),
                    ftpsiteurl = table.Column<string>(type: "TEXT", nullable: true),
                    address1_telephone2 = table.Column<string>(type: "TEXT", nullable: true),
                    tickersymbol = table.Column<string>(type: "TEXT", nullable: true),
                    address1_line2 = table.Column<string>(type: "TEXT", nullable: true),
                    numberofemployees = table.Column<string>(type: "TEXT", nullable: true),
                    aging60_base = table.Column<string>(type: "TEXT", nullable: true),
                    new_sozlesme_baslangic_tarihi = table.Column<string>(type: "TEXT", nullable: true),
                    new_yaz_nufusu = table.Column<string>(type: "TEXT", nullable: true),
                    revenue_base = table.Column<string>(type: "TEXT", nullable: true),
                    openrevenue_base = table.Column<string>(type: "TEXT", nullable: true),
                    marketingonly = table.Column<string>(type: "TEXT", nullable: true),
                    address2_telephone3 = table.Column<string>(type: "TEXT", nullable: true),
                    address1_line3 = table.Column<string>(type: "TEXT", nullable: true),
                    address1_latitude = table.Column<string>(type: "TEXT", nullable: true),
                    new_gizlilik = table.Column<string>(type: "TEXT", nullable: true),
                    address1_telephone1 = table.Column<string>(type: "TEXT", nullable: true),
                    accountnumber = table.Column<string>(type: "TEXT", nullable: true),
                    entityimage_timestamp = table.Column<string>(type: "TEXT", nullable: true),
                    _preferredsystemuserid_value = table.Column<string>(type: "TEXT", nullable: true),
                    address2_postalcode = table.Column<string>(type: "TEXT", nullable: true),
                    preferredappointmentdaycode = table.Column<string>(type: "TEXT", nullable: true),
                    processid = table.Column<string>(type: "TEXT", nullable: true),
                    address2_stateorprovince = table.Column<string>(type: "TEXT", nullable: true),
                    emailaddress3 = table.Column<string>(type: "TEXT", nullable: true),
                    new_verilen_ajanda_adedi = table.Column<string>(type: "TEXT", nullable: true),
                    new_firmaportaldzeyi = table.Column<string>(type: "TEXT", nullable: true),
                    _slainvokedid_value = table.Column<string>(type: "TEXT", nullable: true),
                    aging90 = table.Column<string>(type: "TEXT", nullable: true),
                    sharesoutstanding = table.Column<string>(type: "TEXT", nullable: true),
                    address1_shippingmethodcode = table.Column<string>(type: "TEXT", nullable: true),
                    address2_county = table.Column<string>(type: "TEXT", nullable: true),
                    aging60 = table.Column<string>(type: "TEXT", nullable: true),
                    marketcap = table.Column<string>(type: "TEXT", nullable: true),
                    new_telefon_sure = table.Column<string>(type: "TEXT", nullable: true),
                    accountcategorycode = table.Column<string>(type: "TEXT", nullable: true),
                    aging30_base = table.Column<string>(type: "TEXT", nullable: true),
                    new_mteritemsilcisi = table.Column<string>(type: "TEXT", nullable: true),
                    new_kis_nufusu = table.Column<string>(type: "TEXT", nullable: true),
                    address1_name = table.Column<string>(type: "TEXT", nullable: true),
                    opendeals = table.Column<string>(type: "TEXT", nullable: true),
                    overriddencreatedon = table.Column<string>(type: "TEXT", nullable: true),
                    aging30 = table.Column<string>(type: "TEXT", nullable: true),
                    new_faks2 = table.Column<string>(type: "TEXT", nullable: true),
                    address1_addresstypecode = table.Column<string>(type: "TEXT", nullable: true),
                    address1_fax = table.Column<string>(type: "TEXT", nullable: true),
                    traversedpath = table.Column<string>(type: "TEXT", nullable: true),
                    _parentaccountid_value = table.Column<string>(type: "TEXT", nullable: true),
                    _new_mahalle_value = table.Column<string>(type: "TEXT", nullable: true),
                    new_firmayldnm = table.Column<string>(type: "TEXT", nullable: true),
                    emailaddress1 = table.Column<string>(type: "TEXT", nullable: true),
                    address2_telephone1 = table.Column<string>(type: "TEXT", nullable: true),
                    address1_telephone3 = table.Column<string>(type: "TEXT", nullable: true),
                    new_button = table.Column<string>(type: "TEXT", nullable: true),
                    aging90_base = table.Column<string>(type: "TEXT", nullable: true),
                    new_onayltedariki = table.Column<string>(type: "TEXT", nullable: true),
                    address1_postalcode = table.Column<string>(type: "TEXT", nullable: true),
                    _preferredequipmentid_value = table.Column<string>(type: "TEXT", nullable: true),
                    _owningteam_value = table.Column<string>(type: "TEXT", nullable: true),
                    address2_fax = table.Column<string>(type: "TEXT", nullable: true),
                    lastonholdtime = table.Column<string>(type: "TEXT", nullable: true),
                    creditlimit = table.Column<string>(type: "TEXT", nullable: true),
                    new_ajanda_verilme_tarihi = table.Column<string>(type: "TEXT", nullable: true),
                    address2_country = table.Column<string>(type: "TEXT", nullable: true),
                    followemail = table.Column<string>(type: "TEXT", nullable: true),
                    address2_longitude = table.Column<string>(type: "TEXT", nullable: true),
                    address1_county = table.Column<string>(type: "TEXT", nullable: true),
                    address2_line2 = table.Column<string>(type: "TEXT", nullable: true),
                    revenue = table.Column<string>(type: "TEXT", nullable: true),
                    address2_primarycontactname = table.Column<string>(type: "TEXT", nullable: true),
                    address2_postofficebox = table.Column<string>(type: "TEXT", nullable: true),
                    address1_city = table.Column<string>(type: "TEXT", nullable: true),
                    CrmAccountRootGuid = table.Column<Guid>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CrmAccountValue", x => x.Guid);
                    table.ForeignKey(
                        name: "FK_CrmAccountValue_CrmAccounts_CrmAccountRootGuid",
                        column: x => x.CrmAccountRootGuid,
                        principalTable: "CrmAccounts",
                        principalColumn: "Guid",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CrmAccountValue_CrmAccountRootGuid",
                table: "CrmAccountValue",
                column: "CrmAccountRootGuid");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CrmAccountValue");

            migrationBuilder.RenameColumn(
                name: "OdataNextLink",
                table: "CrmAccounts",
                newName: "OdataEtag");

            migrationBuilder.RenameColumn(
                name: "OdataContext",
                table: "CrmAccounts",
                newName: "Name");

            migrationBuilder.AddColumn<Guid>(
                name: "Accountid",
                table: "CrmAccounts",
                type: "TEXT",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<int>(
                name: "Statecode",
                table: "CrmAccounts",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0);
        }
    }
}
