// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProjectsWithOnionArchitecture.Persist.Persist.Crm.DbContext;

namespace WebProjectsWithOnionArchitecture.Infrastruct.Migrations
{
    [DbContext(typeof(ApplicationCrmDbContext))]
    [Migration("20210517204605_Migration_3")]
    partial class Migration_3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("WebProjectsWithOnionArchitecture.Domain.Entities.App.Entities.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RegisterDateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebProjectsWithOnionArchitecture.Domain.Entities.Crm.Entities.CrmAccountRoot", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("OdataContext")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdataNextLink")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("CrmAccounts");
                });

            modelBuilder.Entity("WebProjectsWithOnionArchitecture.Domain.Entities.Crm.Entities.CrmAccountValue", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CrmAccountRootGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdataEtag")
                        .HasColumnType("TEXT");

                    b.Property<string>("_createdby_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_createdbyexternalparty_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_createdonbehalfby_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_defaultpricelevelid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_masterid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_modifiedby_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_modifiedbyexternalparty_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_modifiedonbehalfby_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_alt_kategori_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_ehirid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_etkinlikprogramid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_firmadepartman_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_ilce_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_kategori_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_lkeid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_mahalle_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_mteritemsilcisiid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_projetakmlar_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_sektorid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_originatingleadid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_ownerid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_owningbusinessunit_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_owningteam_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_owninguser_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_parentaccountid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_preferredequipmentid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_preferredserviceid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_preferredsystemuserid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_primarycontactid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_slaid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_slainvokedid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_territoryid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_transactioncurrencyid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("accountcategorycode")
                        .HasColumnType("TEXT");

                    b.Property<int>("accountclassificationcode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("accountid")
                        .HasColumnType("TEXT");

                    b.Property<string>("accountnumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("accountratingcode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("address1_addressid")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_addresstypecode")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_city")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_composite")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_country")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_county")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_freighttermscode")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_line1")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_line2")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_line3")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_postalcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_postofficebox")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_primarycontactname")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_shippingmethodcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_stateorprovince")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_telephone1")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_telephone2")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_telephone3")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_upszone")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_utcoffset")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_addressid")
                        .HasColumnType("TEXT");

                    b.Property<int>("address2_addresstypecode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("address2_city")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_composite")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_country")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_county")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_fax")
                        .HasColumnType("TEXT");

                    b.Property<int>("address2_freighttermscode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("address2_latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_line1")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_line2")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_line3")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_postalcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_postofficebox")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_primarycontactname")
                        .HasColumnType("TEXT");

                    b.Property<int>("address2_shippingmethodcode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("address2_stateorprovince")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_telephone1")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_telephone2")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_telephone3")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_upszone")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_utcoffset")
                        .HasColumnType("TEXT");

                    b.Property<string>("aging30")
                        .HasColumnType("TEXT");

                    b.Property<string>("aging30_base")
                        .HasColumnType("TEXT");

                    b.Property<string>("aging60")
                        .HasColumnType("TEXT");

                    b.Property<string>("aging60_base")
                        .HasColumnType("TEXT");

                    b.Property<string>("aging90")
                        .HasColumnType("TEXT");

                    b.Property<string>("aging90_base")
                        .HasColumnType("TEXT");

                    b.Property<int>("businesstypecode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("TEXT");

                    b.Property<string>("creditlimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("creditlimit_base")
                        .HasColumnType("TEXT");

                    b.Property<bool>("creditonhold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("customersizecode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("customertypecode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("donotbulkemail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("donotbulkpostalmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("donotemail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("donotfax")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("donotphone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("donotpostalmail")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("donotsendmm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("emailaddress1")
                        .HasColumnType("TEXT");

                    b.Property<string>("emailaddress2")
                        .HasColumnType("TEXT");

                    b.Property<string>("emailaddress3")
                        .HasColumnType("TEXT");

                    b.Property<string>("entityimage")
                        .HasColumnType("TEXT");

                    b.Property<string>("entityimage_timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("entityimage_url")
                        .HasColumnType("TEXT");

                    b.Property<string>("entityimageid")
                        .HasColumnType("TEXT");

                    b.Property<double>("exchangerate")
                        .HasColumnType("REAL");

                    b.Property<string>("fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("followemail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ftpsiteurl")
                        .HasColumnType("TEXT");

                    b.Property<int>("importsequencenumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("industrycode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lastonholdtime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("lastusedincampaign")
                        .HasColumnType("TEXT");

                    b.Property<string>("marketcap")
                        .HasColumnType("TEXT");

                    b.Property<string>("marketcap_base")
                        .HasColumnType("TEXT");

                    b.Property<string>("marketingonly")
                        .HasColumnType("TEXT");

                    b.Property<bool>("merged")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("modifiedon")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_ajanda_verilme_tarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_beldekodu")
                        .HasColumnType("TEXT");

                    b.Property<bool>("new_belgekonumu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("new_button")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_cari_kod")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_cari_unvan")
                        .HasColumnType("TEXT");

                    b.Property<int?>("new_durum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("new_etkinlisanskartisayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("new_faks2")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_firmaportaldzeyi")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_firmayldnm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("new_frsatkayna")
                        .HasColumnType("INTEGER");

                    b.Property<string>("new_gizlilik")
                        .HasColumnType("TEXT");

                    b.Property<int?>("new_gncellemearamas")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("new_gncellemearamasyapld")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("new_gncellemearamatarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_kis_nufusu")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("new_kontroledildi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("new_le")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_lekodu")
                        .HasColumnType("TEXT");

                    b.Property<int?>("new_letiimdili")
                        .HasColumnType("INTEGER");

                    b.Property<string>("new_letiimdili2")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_mteritemsilcisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_onayltedariki")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_randevu_sure")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("new_slavarm")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("new_sonaktivitetarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_sozlesme_baslangic_tarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_sozlesme_bitis_tarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_telefon_sure")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_vergidairesi")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_verginumaras")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_verilen_ajanda_adedi")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_yaz_nufusu")
                        .HasColumnType("TEXT");

                    b.Property<string>("numberofemployees")
                        .HasColumnType("TEXT");

                    b.Property<string>("onholdtime")
                        .HasColumnType("TEXT");

                    b.Property<string>("opendeals")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("opendeals_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("opendeals_state")
                        .HasColumnType("TEXT");

                    b.Property<string>("openrevenue")
                        .HasColumnType("TEXT");

                    b.Property<string>("openrevenue_base")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("openrevenue_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("openrevenue_state")
                        .HasColumnType("TEXT");

                    b.Property<string>("overriddencreatedon")
                        .HasColumnType("TEXT");

                    b.Property<int>("ownershipcode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("participatesinworkflow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("paymenttermscode")
                        .HasColumnType("TEXT");

                    b.Property<string>("preferredappointmentdaycode")
                        .HasColumnType("TEXT");

                    b.Property<string>("preferredappointmenttimecode")
                        .HasColumnType("TEXT");

                    b.Property<int>("preferredcontactmethodcode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("primarysatoriid")
                        .HasColumnType("TEXT");

                    b.Property<string>("primarytwitterid")
                        .HasColumnType("TEXT");

                    b.Property<string>("processid")
                        .HasColumnType("TEXT");

                    b.Property<string>("revenue")
                        .HasColumnType("TEXT");

                    b.Property<string>("revenue_base")
                        .HasColumnType("TEXT");

                    b.Property<string>("sharesoutstanding")
                        .HasColumnType("TEXT");

                    b.Property<string>("shippingmethodcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("sic")
                        .HasColumnType("TEXT");

                    b.Property<string>("stageid")
                        .HasColumnType("TEXT");

                    b.Property<int>("statecode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("statuscode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("stockexchange")
                        .HasColumnType("TEXT");

                    b.Property<string>("telephone1")
                        .HasColumnType("TEXT");

                    b.Property<string>("telephone2")
                        .HasColumnType("TEXT");

                    b.Property<string>("telephone3")
                        .HasColumnType("TEXT");

                    b.Property<int>("territorycode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tickersymbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("timespentbymeonemailandmeetings")
                        .HasColumnType("TEXT");

                    b.Property<int?>("timezoneruleversionnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("traversedpath")
                        .HasColumnType("TEXT");

                    b.Property<string>("utcconversiontimezonecode")
                        .HasColumnType("TEXT");

                    b.Property<string>("versionnumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("websiteurl")
                        .HasColumnType("TEXT");

                    b.Property<string>("yominame")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("CrmAccountRootGuid");

                    b.ToTable("CrmAccountValue");
                });

            modelBuilder.Entity("WebProjectsWithOnionArchitecture.Domain.Entities.Crm.Entities.CrmTask", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegardingObjectidSalesOrderOdataBind")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Scheduledend")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("categoryOfTask")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("CrmTasks");
                });

            modelBuilder.Entity("WebProjectsWithOnionArchitecture.Domain.Entities.Crm.Entities.CrmUser", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("OdataEtag")
                        .HasColumnType("TEXT");

                    b.Property<string>("_businessunitid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_calendarid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_createdby_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_createdonbehalfby_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_defaultmailbox_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_mobileofflineprofileid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_modifiedby_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_modifiedonbehalfby_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_2onayc_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_btsorumlusu_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_doumyeri_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_gm1_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_gm2_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_idari_islersorumlusu_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_ksorumlusu_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_kurumsal_sorumlusu_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_lgilicoo_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_lgiligmy_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_muhasebesorumlusu_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_sekreteryasorumlusu_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_new_takmyneticisi_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_parentsystemuserid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_positionid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_queueid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_siteid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_territoryid_value")
                        .HasColumnType("TEXT");

                    b.Property<string>("_transactioncurrencyid_value")
                        .HasColumnType("TEXT");

                    b.Property<int>("accessmode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("address1_addressid")
                        .HasColumnType("TEXT");

                    b.Property<int>("address1_addresstypecode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("address1_city")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_composite")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_country")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_county")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_line1")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_line2")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_line3")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_postalcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_postofficebox")
                        .HasColumnType("TEXT");

                    b.Property<int>("address1_shippingmethodcode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("address1_stateorprovince")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_telephone1")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_telephone2")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_telephone3")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_upszone")
                        .HasColumnType("TEXT");

                    b.Property<string>("address1_utcoffset")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_addressid")
                        .HasColumnType("TEXT");

                    b.Property<int>("address2_addresstypecode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("address2_city")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_composite")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_country")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_county")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_line1")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_line2")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_line3")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_postalcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_postofficebox")
                        .HasColumnType("TEXT");

                    b.Property<int>("address2_shippingmethodcode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("address2_stateorprovince")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_telephone1")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_telephone2")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_telephone3")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_upszone")
                        .HasColumnType("TEXT");

                    b.Property<string>("address2_utcoffset")
                        .HasColumnType("TEXT");

                    b.Property<string>("applicationid")
                        .HasColumnType("TEXT");

                    b.Property<string>("applicationiduri")
                        .HasColumnType("TEXT");

                    b.Property<string>("azureactivedirectorystringid")
                        .HasColumnType("TEXT");

                    b.Property<int>("caltype")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("defaultfilterspopulated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("defaultodbfoldername")
                        .HasColumnType("TEXT");

                    b.Property<string>("disabledreason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("displayinserviceviews")
                        .HasColumnType("INTEGER");

                    b.Property<string>("domainname")
                        .HasColumnType("TEXT");

                    b.Property<int>("emailrouteraccessapproval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("employeeid")
                        .HasColumnType("TEXT");

                    b.Property<string>("entityimage")
                        .HasColumnType("TEXT");

                    b.Property<string>("entityimage_timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("entityimage_url")
                        .HasColumnType("TEXT");

                    b.Property<string>("entityimageid")
                        .HasColumnType("TEXT");

                    b.Property<double?>("exchangerate")
                        .HasColumnType("REAL");

                    b.Property<string>("firstname")
                        .HasColumnType("TEXT");

                    b.Property<string>("fullname")
                        .HasColumnType("TEXT");

                    b.Property<string>("governmentid")
                        .HasColumnType("TEXT");

                    b.Property<string>("homephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("importsequencenumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("incomingemaildeliverymethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("internalemailaddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("invitestatuscode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isdisabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isemailaddressapprovedbyo365admin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isintegrationuser")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("islicensed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("issyncwithdirectory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("jobtitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastname")
                        .HasColumnType("TEXT");

                    b.Property<string>("middlename")
                        .HasColumnType("TEXT");

                    b.Property<string>("mobilealertemail")
                        .HasColumnType("TEXT");

                    b.Property<string>("mobilephone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("modifiedon")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_acildurumdaulalacakkii")
                        .HasColumnType("TEXT");

                    b.Property<double?>("new_bakiyefark")
                        .HasColumnType("REAL");

                    b.Property<string>("new_bordroadsoyad")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_ceptelefonuzel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("new_dogumgunu")
                        .HasColumnType("TEXT");

                    b.Property<int?>("new_gendercode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("new_ise_giris_tarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("new_isten_cikis_tarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_jobtitleeng")
                        .HasColumnType("TEXT");

                    b.Property<double?>("new_kalanbakiye")
                        .HasColumnType("REAL");

                    b.Property<int?>("new_kangrubu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("new_kullanici_rolu")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_language")
                        .HasColumnType("TEXT");

                    b.Property<double>("new_mazeretzni")
                        .HasColumnType("REAL");

                    b.Property<string>("new_mezuniyetblm")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_mezuniyetokulu")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_mezuniyetyl")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_ncekiyerleri")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_password")
                        .HasColumnType("TEXT");

                    b.Property<int?>("new_portalyetkidzeyi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("new_tecrbesi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("new_timesheet")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("new_timesheetsre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("new_timesheettarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("new_username")
                        .HasColumnType("TEXT");

                    b.Property<string>("nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("organizationid")
                        .HasColumnType("TEXT");

                    b.Property<int>("outgoingemaildeliverymethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("overriddencreatedon")
                        .HasColumnType("TEXT");

                    b.Property<string>("ownerid")
                        .HasColumnType("TEXT");

                    b.Property<string>("passporthi")
                        .HasColumnType("TEXT");

                    b.Property<string>("passportlo")
                        .HasColumnType("TEXT");

                    b.Property<string>("personalemailaddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("photourl")
                        .HasColumnType("TEXT");

                    b.Property<int>("preferredaddresscode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("preferredemailcode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("preferredphonecode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("processid")
                        .HasColumnType("TEXT");

                    b.Property<string>("salutation")
                        .HasColumnType("TEXT");

                    b.Property<bool>("setupuser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sharepointemailaddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("skills")
                        .HasColumnType("TEXT");

                    b.Property<string>("stageid")
                        .HasColumnType("TEXT");

                    b.Property<string>("systemuserid")
                        .HasColumnType("TEXT");

                    b.Property<int?>("timezoneruleversionnumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<string>("traversedpath")
                        .HasColumnType("TEXT");

                    b.Property<int>("userlicensetype")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("utcconversiontimezonecode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("versionnumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("windowsliveid")
                        .HasColumnType("TEXT");

                    b.Property<string>("yammeremailaddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("yammeruserid")
                        .HasColumnType("TEXT");

                    b.Property<string>("yomifirstname")
                        .HasColumnType("TEXT");

                    b.Property<string>("yomifullname")
                        .HasColumnType("TEXT");

                    b.Property<string>("yomilastname")
                        .HasColumnType("TEXT");

                    b.Property<string>("yomimiddlename")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("CrmUsers");
                });

            modelBuilder.Entity("WebProjectsWithOnionArchitecture.Domain.Entities.Crm.Entities.CrmAccountValue", b =>
                {
                    b.HasOne("WebProjectsWithOnionArchitecture.Domain.Entities.Crm.Entities.CrmAccountRoot", null)
                        .WithMany("CrmAccountList")
                        .HasForeignKey("CrmAccountRootGuid");
                });

            modelBuilder.Entity("WebProjectsWithOnionArchitecture.Domain.Entities.Crm.Entities.CrmAccountRoot", b =>
                {
                    b.Navigation("CrmAccountList");
                });
#pragma warning restore 612, 618
        }
    }
}
