// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProjectsWithOnionArchitecture.Persist.DbContext;

namespace WebProjectsWithOnionArchitecture.Infrastruct.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("WebProjectsWithOnionArchitecture.Domain.Crm.Entities.CrmAccount", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Accountid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdataEtag")
                        .HasColumnType("TEXT");

                    b.Property<int>("Statecode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.ToTable("CrmAccount");
                });

            modelBuilder.Entity("WebProjectsWithOnionArchitecture.Domain.Crm.Entities.CrmTask", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegardingObjectidSalesOrderOdataBind")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Scheduledend")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("categoryOfTask")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("CrmTask");
                });

            modelBuilder.Entity("WebProjectsWithOnionArchitecture.Domain.Crm.Entities.CrmUser", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("CrmUser");
                });
#pragma warning restore 612, 618
        }
    }
}
